#ifndef TOURNAMENT_GLOBAL_H
#define TOURNAMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOURNAMENT_LIBRARY)
#  define TOURNAMENT_EXPORT Q_DECL_EXPORT
#else
#  define TOURNAMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // TOURNAMENT_GLOBAL_H
